// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2jnT2v_Lrq7yOFwchVrcVdyy3OkiiWN4',
    appId: '1:499875394751:web:84898a2493c149d15c820a',
    messagingSenderId: '499875394751',
    projectId: 'fypdb-3ce06',
    authDomain: 'fypdb-3ce06.firebaseapp.com',
    storageBucket: 'fypdb-3ce06.appspot.com',
    measurementId: 'G-DYRZG96VZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTMWqtgcqq2EFFisb2ZXKcfLkXC5IZ81o',
    appId: '1:499875394751:android:04d7b4cf1e872a105c820a',
    messagingSenderId: '499875394751',
    projectId: 'fypdb-3ce06',
    storageBucket: 'fypdb-3ce06.appspot.com',
  );
}
